### ISSUE TITLE
[FEATURE REQUEST] Different day selections

### ISSUE THREAD

**Issue by coneybeare** [petulla/Citibike-explorer#1]
Am I right in thinking that changing the days from July 17th would be as simple as swapping out the data sets for existing csvs on the Citi Bike system data page?

**Comment by petulla** [comment]
Read the docs. You have to parse the data ahead of the swap (calculating things like angles and age groups and reducing some of the tail values). I can help you with that. But once the data's in the right format, you'll be set.
